from setuptools import setup

setup(
    name='.factors',
    version='1.0',
    packages=['lib.python3.6.distutils', 'lib.python3.6.encodings', 'lib.python3.6.importlib',
              'lib.python3.6.collections', 'lib.python3.6.site-packages.pip', 'lib.python3.6.site-packages.pip._vendor',
              'lib.python3.6.site-packages.pip._vendor.idna', 'lib.python3.6.site-packages.pip._vendor.pep517',
              'lib.python3.6.site-packages.pip._vendor.pytoml', 'lib.python3.6.site-packages.pip._vendor.certifi',
              'lib.python3.6.site-packages.pip._vendor.chardet', 'lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'lib.python3.6.site-packages.pip._vendor.distlib',
              'lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'lib.python3.6.site-packages.pip._vendor.msgpack', 'lib.python3.6.site-packages.pip._vendor.urllib3',
              'lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'lib.python3.6.site-packages.pip._vendor.colorama', 'lib.python3.6.site-packages.pip._vendor.html5lib',
              'lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'lib.python3.6.site-packages.pip._vendor.lockfile', 'lib.python3.6.site-packages.pip._vendor.progress',
              'lib.python3.6.site-packages.pip._vendor.requests', 'lib.python3.6.site-packages.pip._vendor.packaging',
              'lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'lib.python3.6.site-packages.pip._vendor.webencodings',
              'lib.python3.6.site-packages.pip._vendor.pkg_resources', 'lib.python3.6.site-packages.pip._internal',
              'lib.python3.6.site-packages.pip._internal.cli', 'lib.python3.6.site-packages.pip._internal.req',
              'lib.python3.6.site-packages.pip._internal.vcs', 'lib.python3.6.site-packages.pip._internal.utils',
              'lib.python3.6.site-packages.pip._internal.models', 'lib.python3.6.site-packages.pip._internal.commands',
              'lib.python3.6.site-packages.pip._internal.operations', 'lib.python3.6.site-packages.wheel',
              'lib.python3.6.site-packages.wheel.cli', 'lib.python3.6.site-packages.wtforms',
              'lib.python3.6.site-packages.wtforms.ext', 'lib.python3.6.site-packages.wtforms.ext.csrf',
              'lib.python3.6.site-packages.wtforms.ext.i18n', 'lib.python3.6.site-packages.wtforms.ext.django',
              'lib.python3.6.site-packages.wtforms.ext.django.templatetags',
              'lib.python3.6.site-packages.wtforms.ext.dateutil', 'lib.python3.6.site-packages.wtforms.ext.appengine',
              'lib.python3.6.site-packages.wtforms.ext.sqlalchemy', 'lib.python3.6.site-packages.wtforms.csrf',
              'lib.python3.6.site-packages.wtforms.fields', 'lib.python3.6.site-packages.wtforms.widgets',
              'lib.python3.6.site-packages.intervals', 'lib.python3.6.site-packages.setuptools',
              'lib.python3.6.site-packages.setuptools.extern', 'lib.python3.6.site-packages.setuptools._vendor',
              'lib.python3.6.site-packages.setuptools._vendor.packaging',
              'lib.python3.6.site-packages.setuptools.command', 'lib.python3.6.site-packages.validators',
              'lib.python3.6.site-packages.validators.i18n', 'lib.python3.6.site-packages.pkg_resources',
              'lib.python3.6.site-packages.pkg_resources.extern', 'lib.python3.6.site-packages.pkg_resources._vendor',
              'lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'lib.python3.6.site-packages.wtforms_components',
              'lib.python3.6.site-packages.wtforms_components.fields'],
    url='https://factors.herokuapp.com',
    license='GNU',
    author='KAI',
    author_email='kairosart2007@gmail.com',
    description='Machine Learning for Trading'
)
